### ISSUE TITLE
Execution of ResgateIO.Client.WebSocket.ReceiveLoop halts when returning result

### ISSUE THREAD

**Issue by Sten-V** [jirenius/csharp-resclient#4]
The way `tcs.SetResult(handleRequestResult(result));` is called in this code makes it execute the continuation of the tcs task on the 'library side' and thus blocking library code that would otherwise continue.

https://github.com/jirenius/csharp-resclient/blob/4b0d1b950abf20b1d3e19b9e0dddc50b9c250ed5/ResgateIO.Client/ResClient.cs#L442-L459

That in turn means that this loop will be paused at `MessageReceived(inputStream.ToArray());` until other async code happens to get it going again.

https://github.com/jirenius/csharp-resclient/blob/4b0d1b950abf20b1d3e19b9e0dddc50b9c250ed5/ResgateIO.Client/WebSocket.cs#L73-L104

The loop code effectively waits at `MessageReceived(inputStream.ToArray());` instead of `await ws.ReceiveAsync(new ArraySegment<byte>(buffer), cts.Token);` which I guess means events are not getting through from the other side as intended.

Also the `Dispose()` throws as cts will be null the last time going around to `while (!cts.Token.IsCancellationRequested)`
https://github.com/jirenius/csharp-resclient/blob/4b0d1b950abf20b1d3e19b9e0dddc50b9c250ed5/ResgateIO.Client/WebSocket.cs#L114-L126

A relatively easy fix to this is to change 
https://github.com/jirenius/csharp-resclient/blob/4b0d1b950abf20b1d3e19b9e0dddc50b9c250ed5/ResgateIO.Client/ResClient.cs#L444
to
`TaskCompletionSource<object> tcs = new TaskCompletionSource<object>(TaskCreationOptions.RunContinuationsAsynchronously);`

**Comment by jirenius** [comment]
Admittedly, I still have quite a bit to learn about how .NET schedules its async tasks.

My only concern is whether this will cause race issues. But as far as I can see, there shouldn't be any trouble - especially since events (such as `change` events) are still handled in a serial manner, preventing two quick consecutive events to be handled in the wrong order.

But since `TaskCreationOptions.RunContinuationsAsynchronously` was introduced in 4.6, I will also bump the target framework to 4.8.1 to match that of the service library.

**Comment by jirenius** [comment]
Resolved in PR #5

**Comment by Sten-V** [comment]
Seems I forgot one here
https://github.com/jirenius/csharp-resclient/blob/5cb386e2e8120fa548533fdd12ddb60f5e5b7294/ResgateIO.Client/CacheItem.cs#L23
and here
https://github.com/jirenius/csharp-resclient/blob/5cb386e2e8120fa548533fdd12ddb60f5e5b7294/ResgateIO.Client/ItemCache.cs#L154

Also, since this is library code, I suggest skipping the .NET Framework reference (4.8.1) all together and just stick with .NET Standard 2.0.

Shall I create a PR for any of this?
